### ISSUE TITLE
Mobilus Integration failed sometimes (Caught exception in on_message: 'public_key')

### ISSUE THREAD

**Issue by homeagit** [zpieslak/mobilus-client-home-assistant#19] opened 2024-11-17 16:16 UTC
Sometimes the Integraion stops working. Only a restart of Home Assistant or waiting some minutes helps.

Following error messages I found:

1. 
![image](https://github.com/user-attachments/assets/0fef386a-2cd7-44c2-ae12-efd10f26a331)
2. 
![image](https://github.com/user-attachments/assets/69e75311-9732-464f-983f-47118df098f6)
3. 
![image](https://github.com/user-attachments/assets/f5ec971a-f82b-458f-aa41-face31f04d89)
4. Logger: mobilus_client.client
Quelle: custom_components/mobilus/coordinator.py:59
Integration: mobilus ([Dokumentation](https://github.com/zpieslak/mobilus-client-home-assistant), [Probleme](https://github.com/zpieslak/mobilus-client-home-assistant/issues))
Erstmals aufgetreten: 17:19:48 (1 Vorkommnisse)
Zuletzt protokolliert: 17:19:48

Failed to authenticate with the gateway host
5. Logger: custom_components.mobilus.coordinator
Quelle: helpers/update_coordinator.py:414
Integration: mobilus ([Dokumentation](https://github.com/zpieslak/mobilus-client-home-assistant), [Probleme](https://github.com/zpieslak/mobilus-client-home-assistant/issues))
Erstmals aufgetreten: 17:19:48 (1 Vorkommnisse)
Zuletzt protokolliert: 17:19:48

Error fetching mobilus_coordinator data:

**Comment by zpieslak** [comment] 2024-11-17 17:52
@homeagit Thank you for your detiled report. I can confirm that I can reproduce issue 2 "Caught exception in on_message: 'public_key'". Let me see how this could be fixed. I will update this thread.

Regarding the first message: `Detected that integration 'mobilus' uses async_config_entry_first_refresh, which is only supported for coordinators with a config entry and will stop working in Home Assistant 2025.11`. It is deprecation warning and should not make any issues, however I will fix it too in separate task.

**Comment by zpieslak** [comment] 2024-11-20 18:59
@homeagit Please check the main branch and let me know if it works for you. I belive the issue should be solved.

**Comment by homeagit** [comment] 2024-11-22 07:04
After installing latest version I tried to open all shutters. the result was the same. public_key errors as shown above

**Comment by zpieslak** [comment] 2024-11-22 16:11
@homeagit Apologies I wasn't clear enoguh. The latest version was in main git branch, so if you are using hacs it may not work. However I created a new reelease (v0.2.1). Can you try it? Also what home assistant version are you using? I cannot reproduce that [deprecation warning](https://github.com/zpieslak/mobilus-client-home-assistant/issues/20).

**Comment by homeagit** [comment] 2024-11-22 17:18
@zpieslak: I used the new release (v0.2.1) and now it works without any errors and the integration is still available after moving the shutters. Again a big Thank You, great work!
The deprecation warning was already done before the new release, I had overlooked that

**Comment by zpieslak** [comment] 2024-11-22 17:48
Great! Thank for testing, I will close the issue then.

**Closed by zpieslak** 2024-11-22 17:48 UTC
